# Generated by Django 5.2.8 on 2025-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
